Repository PerFumeOnMe/Back-end, pull requests merged in 2025-08, with the labels that each got.

#117 [CICD] #116 ec2에서 fastapi와 통신하도록 설정
  .github/workflows/dev_deploy.yml
  src/main/resources/application-dev.yml
Labels: :earth_asia: CI/CD

#118 [ci-cd] docker network bridge 추가(#116)
  .github/workflows/dev_deploy.yml
Labels: :earth_asia: CI/CD, :hammer: Fix

#119 [fix]#116- network 중복 설정 수정
  .github/workflows/dev_deploy.yml
Labels: :earth_asia: CI/CD, :hammer: Fix

#120 [fix]#116- pbti, 이미지키워드 Fastapi url 수정
  .github/workflows/dev_deploy.yml
  src/main/resources/application-dev.yml
Labels: :bug: Bug, :earth_asia: CI/CD, :hammer: Fix

#124 [Feature] #123 - 메인페이지 나만의향수 조회 API 구현
  src/main/java/PerfumeOnMe/spring/converter/FragranceConverter.java
  src/main/java/PerfumeOnMe/spring/repository/imagekeyword/ImageKeywordRepository.java
  src/main/java/PerfumeOnMe/spring/repository/workshop/WorkshopRepository.java
  src/main/java/PerfumeOnMe/spring/service/fragrance/FragranceService.java
  src/main/java/PerfumeOnMe/spring/service/fragrance/FragranceServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/FragranceController.java
  src/main/java/PerfumeOnMe/spring/web/dto/fragrance/FragranceResponseDTO.java
Labels: :sparkles: Feature

#126 [Hotfix] application-dev파일 수정
  src/main/resources/application-dev.yml
Labels: :hammer: Fix

#128 [Fix] #91 - 카카오 소셜 로그인 Http Method 수정
  src/main/java/PerfumeOnMe/spring/config/security/SecurityConfig.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/filter/JwtAuthenticationFilter.java
  src/main/java/PerfumeOnMe/spring/config/security/oauth/controller/OAuthController.java
Labels: :hammer: Fix

#130 [Fix]#129 - 챗봇 492 에러 예외처리
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/PerfumeOnMe/spring/converter/ChatConverter.java
  src/main/java/PerfumeOnMe/spring/service/chatbot/ChatbotServiceImpl.java
  src/main/resources/prompts/expert.txt
Labels: :hammer: Fix

#127 [Fix] #98 - PBTI 결과 조회 기능 수정
  src/main/java/PerfumeOnMe/spring/service/external/FastApiClient.java
  src/main/java/PerfumeOnMe/spring/service/openAi/OpenAiService.java
  src/main/java/PerfumeOnMe/spring/service/openAi/PromptBuilder.java
  src/main/java/PerfumeOnMe/spring/service/pbti/PbtiScoringUtil.java
  src/main/java/PerfumeOnMe/spring/service/pbti/PbtiServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/dto/external/FastApiPbtiRecommendResponse.java
Labels: :hammer: Fix

#150 [Fix] #115 데이터시트 - Brand enum 타입 추가
  src/main/java/PerfumeOnMe/spring/common/enums/Brand.java
  src/main/java/PerfumeOnMe/spring/common/fragranceInit/FragranceRowProcessor.java
Labels: :hammer: Fix

#154 [Fix] #153 - 일반/소셜 로그인 API 응답값 수정
  src/main/java/PerfumeOnMe/spring/security/auth/converter/AuthConverter.java
  src/main/java/PerfumeOnMe/spring/security/auth/docs/LoginControllerDocs.java
  src/main/java/PerfumeOnMe/spring/security/auth/dto/AuthRequestDTO.java
  src/main/java/PerfumeOnMe/spring/security/auth/dto/AuthResponseDTO.java
  src/main/java/PerfumeOnMe/spring/security/auth/filter/JwtLoginFilter.java
  src/main/java/PerfumeOnMe/spring/security/auth/service/LoginServiceImpl.java
  src/main/java/PerfumeOnMe/spring/security/oauth/docs/OAuthControllerDocs.java
Labels: :pen: Docs, :hammer: Fix

#158 [Hotfix] #156- 향수공방 노트 오타 수정
  src/main/java/PerfumeOnMe/spring/workshop/validation/annotation/ValidTopNote.java
  src/main/java/PerfumeOnMe/spring/workshop/validation/validator/ValidTopNoteValidator.java
Labels: :hammer: Fix

#160 [Fix] 카카오 소셜 로그인 리다이렉트 URI 경로 수정
  src/main/resources/application-dev.yml
Labels: :hammer: Fix

#161 [Feature] #159 - 나만의 향수 배경제거한 향수 이미지 반환
  src/main/java/PerfumeOnMe/spring/external/fastapi/dto/FastApiRecommendResponse.java
  src/main/java/PerfumeOnMe/spring/fragrance/service/FragranceServiceImpl.java
  src/main/java/PerfumeOnMe/spring/fragrance/web/dto/FragranceResponseDTO.java
  src/main/java/PerfumeOnMe/spring/imagekeyword/service/ImageKeywordPreviewService.java
  src/main/java/PerfumeOnMe/spring/imagekeyword/web/dto/ImageKeywordResponseDTO.java
  src/main/java/PerfumeOnMe/spring/workshop/converter/WorkshopConverter.java
  src/main/java/PerfumeOnMe/spring/workshop/domain/WorkshopFragrance.java
  src/main/java/PerfumeOnMe/spring/workshop/web/dto/WorkshopResponseDTO.java
  src/main/resources/data/perfumeOnMe_data.xlsx
Labels: :sparkles: Feature, :hammer: Fix

#164 [Fix] #162 데이터시트 - 최신 데이터시트 업데이트
  src/main/java/PerfumeOnMe/spring/common/config/WebClientConfig.java
  src/main/resources/data/perfumeOnMe_data.xlsx
Labels: :hammer: Fix

#175 [CI/CD] dev 작업 내용 main 반영
  src/main/java/PerfumeOnMe/spring/pbti/service/PbtiService.java
  src/main/java/PerfumeOnMe/spring/pbti/service/PbtiServiceImpl.java
  src/main/java/PerfumeOnMe/spring/pbti/web/controller/PbtiController.java
  src/main/java/PerfumeOnMe/spring/pbti/web/docs/PbtiControllerDocs.java
  src/main/java/PerfumeOnMe/spring/security/SecurityConfig.java
Labels: :earth_asia: CI/CD
