Repository PerFumeOnMe/Back-end, pull requests merged in 2025-07, with the labels that each got.

#10 [Feature] #9 - 자체 회원가입 API 구현
  .gitignore
  build.gradle
  src/main/java/PerfumeOnMe/spring/apiPayload/ApiResponse.java
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/PerfumeOnMe/spring/config/security/SecurityConfig.java
  src/main/java/PerfumeOnMe/spring/converter/UserConverter.java
  src/main/java/PerfumeOnMe/spring/domain/User.java
  src/main/java/PerfumeOnMe/spring/domain/enums/UserStatus.java
  src/main/java/PerfumeOnMe/spring/repository/user/UserRepository.java
  src/main/java/PerfumeOnMe/spring/service/user/UserService.java
  src/main/java/PerfumeOnMe/spring/service/user/UserServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/UserController.java
  src/main/java/PerfumeOnMe/spring/web/dto/user/UserRequestDTO.java
  src/main/java/PerfumeOnMe/spring/web/dto/user/UserResponseDTO.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: :bug: Bug, :sparkles: Feature, :art: Style, :hammer: Fix, :wrench: Chore

#11 [Feature] #8 - 데이터시트 저장 API
  build.gradle
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/PerfumeOnMe/spring/domain/Fragrance.java
  src/main/java/PerfumeOnMe/spring/domain/ImageKeyword.java
  src/main/java/PerfumeOnMe/spring/domain/Note.java
  src/main/java/PerfumeOnMe/spring/domain/Price.java
  src/main/java/PerfumeOnMe/spring/domain/Workshop.java
  src/main/java/PerfumeOnMe/spring/domain/enums/Brand.java
  src/main/java/PerfumeOnMe/spring/domain/enums/FragranceGender.java
  src/main/java/PerfumeOnMe/spring/domain/enums/FragranceType.java
  src/main/java/PerfumeOnMe/spring/domain/enums/NoteType.java
  src/main/java/PerfumeOnMe/spring/domain/mapping/FragrancePrice.java
  src/main/java/PerfumeOnMe/spring/domain/mapping/RecommendedFragrance.java
  src/main/java/PerfumeOnMe/spring/repository/fragrance/FragranceRepository.java
  src/main/java/PerfumeOnMe/spring/repository/fragrance/FragranceRepositoryCustom.java
  src/main/java/PerfumeOnMe/spring/repository/fragrance/FragranceRepositoryImpl.java
  src/main/java/PerfumeOnMe/spring/repository/fragranceBaseNote/FragranceBaseNoteRepository.java
  src/main/java/PerfumeOnMe/spring/repository/fragranceBaseNote/FragranceBaseNoteRepositoryCustom.java
  src/main/java/PerfumeOnMe/spring/repository/fragranceBaseNote/FragranceBaseNoteRepositoryImpl.java
  src/main/java/PerfumeOnMe/spring/repository/fragranceLocation/FragranceLocationRepository.java
  src/main/java/PerfumeOnMe/spring/repository/fragranceLocation/FragranceLocationRepositoryCustom.java
  src/main/java/PerfumeOnMe/spring/repository/fragranceLocation/FragranceLocationRepositoryImpl.java
  src/main/java/PerfumeOnMe/spring/repository/fragranceMiddleNote/FragranceMiddleNoteRepository.java
  src/main/java/PerfumeOnMe/spring/repository/fragranceMiddleNote/FragranceMiddleNoteRepositoryCustom.java
  src/main/java/PerfumeOnMe/spring/repository/fragranceMiddleNote/FragranceMiddleNoteRepositoryImpl.java
  src/main/java/PerfumeOnMe/spring/repository/fragrancePrice/FragrancePriceRepository.java
  src/main/java/PerfumeOnMe/spring/repository/fragrancePrice/FragrancePriceRepositoryCustom.java
  src/main/java/PerfumeOnMe/spring/repository/fragrancePrice/FragrancePriceRepositoryImpl.java
  src/main/java/PerfumeOnMe/spring/repository/fragranceSeason/FragranceSeasonRepository.java
  src/main/java/PerfumeOnMe/spring/repository/fragranceSeason/FragranceSeasonRepositoryCustom.java
  src/main/java/PerfumeOnMe/spring/repository/fragranceSeason/FragranceSeasonRepositoryImpl.java
  src/main/java/PerfumeOnMe/spring/repository/fragranceTopNote/FragranceTopNoteRepository.java
  src/main/java/PerfumeOnMe/spring/repository/fragranceTopNote/FragranceTopNoteRepositoryCustom.java
  src/main/java/PerfumeOnMe/spring/repository/fragranceTopNote/FragranceTopNoteRepositoryImpl.java
  src/main/java/PerfumeOnMe/spring/repository/location/LocationRepository.java
  src/main/java/PerfumeOnMe/spring/repository/location/LocationRepositoryCustom.java
  src/main/java/PerfumeOnMe/spring/repository/location/LocationRepositoryImpl.java
  src/main/java/PerfumeOnMe/spring/repository/note/NoteRepository.java
  src/main/java/PerfumeOnMe/spring/repository/note/NoteRepositoryCustom.java
  src/main/java/PerfumeOnMe/spring/repository/note/NoteRepositoryImpl.java
  src/main/java/PerfumeOnMe/spring/repository/price/PriceRepository.java
  src/main/java/PerfumeOnMe/spring/repository/price/PriceRepositoryCustom.java
  src/main/java/PerfumeOnMe/spring/repository/price/PriceRepositoryImpl.java
  src/main/java/PerfumeOnMe/spring/repository/season/SeasonRepository.java
  src/main/java/PerfumeOnMe/spring/repository/season/SeasonRepositoryCustom.java
  src/main/java/PerfumeOnMe/spring/repository/season/SeasonRepositoryImpl.java
  src/main/java/PerfumeOnMe/spring/service/fragranceInit/FragranceImportService.java
  src/main/java/PerfumeOnMe/spring/service/fragranceInit/FragranceRowProcessor.java
  src/main/java/PerfumeOnMe/spring/web/controller/RootController.java
  src/main/resources/data/.DS_Store
  src/main/resources/data/perfumeOnMe_data.xlsx
Labels: :sparkles: Feature, :hammer: Fix

#15 [Feature] #13 - 향수 상세페이지 조회 API
  gradlew
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/PerfumeOnMe/spring/converter/FragranceConverter.java
  src/main/java/PerfumeOnMe/spring/domain/Terms.java
  src/main/java/PerfumeOnMe/spring/domain/enums/Brand.java
  src/main/java/PerfumeOnMe/spring/domain/mapping/FragrancePrice.java
  src/main/java/PerfumeOnMe/spring/repository/fragrance/FragranceRepositoryCustom.java
  src/main/java/PerfumeOnMe/spring/repository/fragrance/FragranceRepositoryImpl.java
  src/main/java/PerfumeOnMe/spring/service/fragrance/FragranceService.java
  src/main/java/PerfumeOnMe/spring/service/fragrance/FragranceServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/FragranceController.java
  src/main/java/PerfumeOnMe/spring/web/dto/fragrance/FragranceResponseDTO.java
Labels: :sparkles: Feature

#19 [Feature] #16 - 향수 검색 API 구현
  src/main/java/PerfumeOnMe/spring/converter/FragranceConverter.java
  src/main/java/PerfumeOnMe/spring/repository/fragrance/FragranceRepositoryCustom.java
  src/main/java/PerfumeOnMe/spring/repository/fragrance/FragranceRepositoryImpl.java
  src/main/java/PerfumeOnMe/spring/service/fragrance/FragranceService.java
  src/main/java/PerfumeOnMe/spring/service/fragrance/FragranceServiceImpl.java
  src/main/java/PerfumeOnMe/spring/validation/annotation/ValidKeyword.java
  src/main/java/PerfumeOnMe/spring/validation/annotation/ValidPage.java
  src/main/java/PerfumeOnMe/spring/validation/annotation/ValidSize.java
  src/main/java/PerfumeOnMe/spring/validation/validator/PageValidator.java
  src/main/java/PerfumeOnMe/spring/validation/validator/SizeValidator.java
  src/main/java/PerfumeOnMe/spring/validation/validator/ValidKeywordValidator.java
  src/main/java/PerfumeOnMe/spring/web/controller/FragranceController.java
  src/main/java/PerfumeOnMe/spring/web/dto/fragrance/FragranceRequestDTO.java
  src/main/java/PerfumeOnMe/spring/web/dto/fragrance/FragranceResponseDTO.java
  src/main/resources/application-dev.yml
Labels: :sparkles: Feature, :hammer: Fix

#17 [Feature] #12 - JWT 로그인 및 토큰 재발급 API 구현
  src/main/java/PerfumeOnMe/spring/apiPayload/ApiResponse.java
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/PerfumeOnMe/spring/apiPayload/exception/GeneralException.java
  src/main/java/PerfumeOnMe/spring/config/RedisConfig.java
  src/main/java/PerfumeOnMe/spring/config/security/AuthenticationManagerConfig.java
  src/main/java/PerfumeOnMe/spring/config/security/PasswordEncoderConfig.java
  src/main/java/PerfumeOnMe/spring/config/security/SecurityConfig.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/dto/AuthRequestDTO.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/dto/AuthResponseDTO.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/dto/JwtProperties.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/filter/JwtAuthenticationFilter.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/filter/JwtExceptionHandlerFilter.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/filter/JwtLoginFilter.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/handler/JwtAccessDeniedHandler.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/handler/JwtAuthenticationEntryPoint.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/manager/RefreshTokenManager.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/provider/CustomLoginAuthenticationProvider.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/provider/JwtAuthenticationProvider.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/provider/JwtTokenProvider.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/token/JwtAuthenticationToken.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/userDetails/CustomUserDetails.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/userDetails/CustomUserDetailsService.java
  src/main/java/PerfumeOnMe/spring/service/user/UserService.java
  src/main/java/PerfumeOnMe/spring/service/user/UserServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/UserController.java
  src/main/java/PerfumeOnMe/spring/web/dto/user/UserRequestDTO.java
  src/main/resources/application-dev.yml
Labels: :bug: Bug, :sparkles: Feature, :art: Style, :hammer: Fix

#23 [Feature] #18 - 로그아웃 및 회원탈퇴 API 구현
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/PerfumeOnMe/spring/config/security/SecurityConfig.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/filter/JwtAuthenticationFilter.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/filter/JwtLoginFilter.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/manager/LogoutAccessTokenManager.java
  src/main/java/PerfumeOnMe/spring/service/user/UserService.java
  src/main/java/PerfumeOnMe/spring/service/user/UserServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/UserController.java
Labels: :sparkles: Feature, :hammer: Fix

#29 [Feature] #21 - 향수 즐겨찾기 등록 API 구현
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/PerfumeOnMe/spring/converter/FragranceConverter.java
  src/main/java/PerfumeOnMe/spring/repository/fragrance/FragranceRepository.java
  src/main/java/PerfumeOnMe/spring/repository/user/UserRepository.java
  src/main/java/PerfumeOnMe/spring/repository/userFragrance/UserFragranceRepository.java
  src/main/java/PerfumeOnMe/spring/service/fragrance/FragranceService.java
  src/main/java/PerfumeOnMe/spring/service/fragrance/FragranceServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/FragranceController.java
  src/main/java/PerfumeOnMe/spring/web/dto/fragrance/FragranceResponseDTO.java
Labels: :sparkles: Feature

#34 [Feature] #33 - 향수 조회 시 즐겨찾기 TF 추가
  src/main/java/PerfumeOnMe/spring/converter/FragranceConverter.java
  src/main/java/PerfumeOnMe/spring/repository/userFragrance/UserFragranceRepository.java
  src/main/java/PerfumeOnMe/spring/service/fragrance/FragranceService.java
  src/main/java/PerfumeOnMe/spring/service/fragrance/FragranceServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/FragranceController.java
  src/main/java/PerfumeOnMe/spring/web/dto/fragrance/FragranceResponseDTO.java
Labels: :sparkles: Feature, :hammer: Fix

#37 [Feature] #36 - 향수 상세 페이지 - ImageURL 추가
  src/main/java/PerfumeOnMe/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/PerfumeOnMe/spring/converter/FragranceConverter.java
  src/main/java/PerfumeOnMe/spring/web/dto/fragrance/FragranceResponseDTO.java
Labels: :hammer: Fix

#39 [Feature] #38 - 향수 전체 리스트 API 구현
  src/main/java/PerfumeOnMe/spring/config/security/SecurityConfig.java
  src/main/java/PerfumeOnMe/spring/service/fragrance/FragranceService.java
  src/main/java/PerfumeOnMe/spring/service/fragrance/FragranceServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/FragranceController.java
  src/main/java/PerfumeOnMe/spring/web/dto/fragrance/FragranceRequestDTO.java
Labels: :sparkles: Feature, :hammer: Fix

#42 [CI/CD] #41 - CI/CD 파이프라인 구축(2)
  .github/workflows/dev_deploy.yml
  .gitignore
  Dockerfile
  src/main/resources/application-dev.yml
Labels: :earth_asia: CI/CD

#44 [CI/CD] #41 - CI/CD 파이프라인 구축(테스트2)
  src/main/resources/application-dev.yml
Labels: :earth_asia: CI/CD

#46 [CI/CD] #41 RDS, Redis 설정
  src/main/resources/application-dev.yml
Labels: :earth_asia: CI/CD

#49 [CI/CD] #41 - CI/CD 파이프라인 구축 테스트(3)
  .github/workflows/dev_deploy.yml
  src/main/resources/application-dev.yml
Labels: :earth_asia: CI/CD

#50 [CI/CD] #41 dev_deploy.yml에 프로필설정 추가 (테스트4)
  .github/workflows/dev_deploy.yml
Labels: :earth_asia: CI/CD

#52 [CI/CD] #41 ci/cd (테스트4)
  src/main/resources/application-dev.yml
Labels: :earth_asia: CI/CD

#55 [CI/CD] #41 env블록에 secret정의하고 변수명으로 참조 추가
  .github/workflows/dev_deploy.yml
Labels: :sparkles: Feature

#59 [CI/CD] 연결테스트 완료 후 ddl-auto update수정(#41)
  src/main/resources/application-dev.yml
Labels: :earth_asia: CI/CD, :white_check_mark: Test

#62 [Bug] #48 - GitHub PR 동작 확인
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/ErrorStatus.java
Labels: :bug: Bug

#66 [Feature] #65 - 다이어리 수정 API 구현
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/PerfumeOnMe/spring/domain/mapping/Diary.java
  src/main/java/PerfumeOnMe/spring/service/Diary/DiaryService.java
  src/main/java/PerfumeOnMe/spring/service/Diary/DiaryServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/DiaryController.java
  src/main/java/PerfumeOnMe/spring/web/dto/diary/DiaryRequestDTO.java
Labels: :sparkles: Feature

#68 [Feature] #67 - 다이어리 삭제 API 구현
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/PerfumeOnMe/spring/service/Diary/DiaryService.java
  src/main/java/PerfumeOnMe/spring/service/Diary/DiaryServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/DiaryController.java
Labels: :sparkles: Feature

#70 [Feature] #69 - 일별 다이어리 상세 조회 API 구현
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/PerfumeOnMe/spring/repository/diary/DiaryRepository.java
  src/main/java/PerfumeOnMe/spring/service/Diary/DiaryService.java
  src/main/java/PerfumeOnMe/spring/service/Diary/DiaryServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/DiaryController.java
  src/main/java/PerfumeOnMe/spring/web/dto/diary/DiaryResponseDTO.java
Labels: :sparkles: Feature

#72 [Feature] 월별 다이어리 조회 API 구현 (#71)
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/PerfumeOnMe/spring/repository/diary/DiaryRepository.java
  src/main/java/PerfumeOnMe/spring/service/Diary/DiaryService.java
  src/main/java/PerfumeOnMe/spring/service/Diary/DiaryServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/DiaryController.java
  src/main/java/PerfumeOnMe/spring/web/dto/diary/DiaryResponseDTO.java
Labels: :sparkles: Feature

#75 [Feature] S3 설정, Presigned URL발급 API 구현
  build.gradle
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/PerfumeOnMe/spring/aws/s3/AmazonS3Manager.java
  src/main/java/PerfumeOnMe/spring/config/AmazonConfig.java
  src/main/java/PerfumeOnMe/spring/converter/S3Converter.java
  src/main/java/PerfumeOnMe/spring/domain/Uuid.java
  src/main/java/PerfumeOnMe/spring/repository/uuid/UuidRepository.java
  src/main/java/PerfumeOnMe/spring/web/controller/S3Controller.java
  src/main/java/PerfumeOnMe/spring/web/dto/s3/s3RequestDTO.java
  src/main/java/PerfumeOnMe/spring/web/dto/s3/s3ResponseDTO.java
  src/main/resources/application-dev.yml
Labels: :sparkles: Feature

#81 [Feature] #73 - PBTI 결과 조회 API 구현
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/PerfumeOnMe/spring/config/WebClientConfig.java
  src/main/java/PerfumeOnMe/spring/domain/PBTI.java
  src/main/java/PerfumeOnMe/spring/repository/pbti/PbtiRepository.java
  src/main/java/PerfumeOnMe/spring/service/diary/DiaryService.java
  src/main/java/PerfumeOnMe/spring/service/diary/DiaryServiceImpl.java
  src/main/java/PerfumeOnMe/spring/service/openAi/OpenAiApiClient.java
  src/main/java/PerfumeOnMe/spring/service/openAi/OpenAiService.java
  src/main/java/PerfumeOnMe/spring/service/openAi/OpenAiServiceImpl.java
  src/main/java/PerfumeOnMe/spring/service/openAi/PromptBuilder.java
  src/main/java/PerfumeOnMe/spring/service/pbti/PbtiScoringUtil.java
  src/main/java/PerfumeOnMe/spring/service/pbti/PbtiService.java
  src/main/java/PerfumeOnMe/spring/service/pbti/PbtiServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/DiaryController.java
  src/main/java/PerfumeOnMe/spring/web/controller/PbtiController.java
  src/main/java/PerfumeOnMe/spring/web/dto/Pbti/ChatGptRequest.java
  src/main/java/PerfumeOnMe/spring/web/dto/Pbti/ChatGptResponse.java
  src/main/java/PerfumeOnMe/spring/web/dto/Pbti/PbtiRequestDTO.java
  src/main/java/PerfumeOnMe/spring/web/dto/Pbti/PbtiResponseDTO.java
Labels: :sparkles: Feature

#85 [Feature] #84 - 마이페이지 PBTI 목록 조회 API 구현
  src/main/java/PerfumeOnMe/spring/converter/PbtiConverter.java
  src/main/java/PerfumeOnMe/spring/repository/pbti/PbtiRepository.java
  src/main/java/PerfumeOnMe/spring/service/pbti/PbtiService.java
  src/main/java/PerfumeOnMe/spring/service/pbti/PbtiServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/PbtiController.java
  src/main/java/PerfumeOnMe/spring/web/dto/Pbti/PbtiResponseDTO.java
Labels: :sparkles: Feature

#87 [Feature] #86 - 마이페이지 PBTI 결과 상세 조회 API 구현
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/PerfumeOnMe/spring/converter/PbtiConverter.java
  src/main/java/PerfumeOnMe/spring/service/pbti/PbtiService.java
  src/main/java/PerfumeOnMe/spring/service/pbti/PbtiServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/PbtiController.java
  src/main/java/PerfumeOnMe/spring/web/dto/Pbti/PbtiRequestDTO.java
  src/main/java/PerfumeOnMe/spring/web/dto/Pbti/PbtiResponseDTO.java
Labels: :sparkles: Feature

#89 [Feature] #80- fastapi 미정으로 인한 예외처리 추가
  .github/workflows/dev_deploy.yml
  src/main/java/PerfumeOnMe/spring/service/external/FastApiClient.java
  src/main/resources/application-dev.yml
Labels: :earth_asia: CI/CD, :hammer: Fix

#95 [Refactor] #91 - 로그인 처리를 필터에서 컨트롤러로 변경
  src/main/java/PerfumeOnMe/spring/config/security/SecurityConfig.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/controller/LoginController.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/dto/AuthRequestDTO.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/filter/JwtLoginFilter.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/service/LoginService.java
  src/main/java/PerfumeOnMe/spring/config/security/auth/service/LoginServiceImpl.java
  src/main/java/PerfumeOnMe/spring/service/user/UserServiceImpl.java
Labels: :recycle: Refactor, :hammer: Fix

#97 [Refactor] #92 - PBTI 결과 조회, 상세 조회 API 수정
  src/main/java/PerfumeOnMe/spring/service/external/FastApiClient.java
  src/main/java/PerfumeOnMe/spring/service/openAi/PromptBuilder.java
  src/main/java/PerfumeOnMe/spring/service/pbti/PbtiServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/dto/Pbti/PbtiResponseDTO.java
  src/main/java/PerfumeOnMe/spring/web/dto/external/FastApiPbtiRecommendResponse.java
  src/main/java/PerfumeOnMe/spring/web/dto/external/FastApiRecommendRequest.java
Labels: :recycle: Refactor

#99 [Feature] #98 - PBTI 결과 이름 수정, 결과 삭제 API 구현
  src/main/java/PerfumeOnMe/spring/converter/PbtiConverter.java
  src/main/java/PerfumeOnMe/spring/domain/PBTI.java
  src/main/java/PerfumeOnMe/spring/service/pbti/PbtiService.java
  src/main/java/PerfumeOnMe/spring/service/pbti/PbtiServiceImpl.java
  src/main/java/PerfumeOnMe/spring/web/controller/PbtiController.java
  src/main/java/PerfumeOnMe/spring/web/dto/Pbti/PbtiRequestDTO.java
  src/main/java/PerfumeOnMe/spring/web/dto/Pbti/PbtiResponseDTO.java
Labels: :sparkles: Feature

#101 [Feature] #94 - 향수공방 결과 미리보기(생성)/저장 구현
  src/main/java/PerfumeOnMe/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/PerfumeOnMe/spring/converter/WorkshopConverter.java
  src/main/java/PerfumeOnMe/spring/domain/WorkshopFragrance.java
  src/main/java/PerfumeOnMe/spring/repository/WorkshopFragranceRepository.java
  src/main/java/PerfumeOnMe/spring/repository/workshop/WorkshopRepository.java
  src/main/java/PerfumeOnMe/spring/service/openAi/OpenAiService.java
  src/main/java/PerfumeOnMe/spring/service/openAi/OpenAiServiceImpl.java
  src/main/java/PerfumeOnMe/spring/service/redis/WorkshopRedisService.java
  src/main/java/PerfumeOnMe/spring/service/workshop/WorkshopRecommendationService.java
  src/main/java/PerfumeOnMe/spring/service/workshop/WorkshopResult.java
  src/main/java/PerfumeOnMe/spring/service/workshop/WorkshopResultParser.java
  src/main/java/PerfumeOnMe/spring/service/workshop/WorkshopService.java
  src/main/java/PerfumeOnMe/spring/web/controller/WorkshopController.java
  src/main/java/PerfumeOnMe/spring/web/dto/workshop/WorkshopRequestDTO.java
  src/main/java/PerfumeOnMe/spring/web/dto/workshop/WorkshopResponseDTO.java
  src/main/resources/application-dev.yml
  src/main/resources/prompts/workshop.txt
Labels: :sparkles: Feature

#103 [Fix] #91 - 액세스 토큰 만료 시간 2주로 변경
  src/main/resources/application-dev.yml
Labels: :hammer: Fix

#104 [Hotfix] Redis 설정오류 해결
  src/main/resources/application-dev.yml
Labels: :hammer: Fix

#110 [Fix] #109 - 데이터시트 관련 파일 및 코드 수정
  src/main/java/PerfumeOnMe/spring/apiPayload/exception/GeneralException.java
  src/main/java/PerfumeOnMe/spring/domain/Fragrance.java
  src/main/java/PerfumeOnMe/spring/domain/enums/Brand.java
  src/main/java/PerfumeOnMe/spring/service/fragranceInit/FragranceImportService.java
  src/main/java/PerfumeOnMe/spring/service/fragranceInit/FragranceRowProcessor.java
  src/main/resources/data/perfumeOnMe_data.xlsx
  src/main/resources/prompts/expert.txt
Labels: :hammer: Fix
